name: Build and Package ClamshellMode

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build ClamshellMode
        run: msbuild ClamshellMode.sln /p:Configuration=Release /p:Platform=x64
        timeout-minutes: 30

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: x64/Release/ClamshellMode.exe
